# Generated by Django 5.2.4 on 2025-07-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mens Unstitched', 'Mens Unstitched'), ('Mens stitched', 'Mens stitched'), ('Mens Shawls', 'Mens Shawls'), ('Womens Unstitched', 'Womens Unstitched'), ('Womens Unstitched', 'Womens Unstitched'), ('Womens Shawls', 'Womens Shawls'), ('Electronics', 'Electronics'), ('Watches', 'Watches'), ('Headphones', 'Headphones'), ('Earbuds', 'Earbuds')], default='Mens', max_length=20),
        ),
    ]
