# Generated by Django 5.2.4 on 2025-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mens_Unstitched', 'Mens_Unstitched'), ('Mens_stitched', 'Mens_stitched'), ('Mens_Shawls', 'Mens_Shawls'), ('Womens_Unstitched', 'Womens_Unstitched'), ('Womens_stitched', 'Womens_stitched'), ('Womens_Shawls', 'Womens_Shawls'), ('Watches', 'Watches'), ('Headphones', 'Headphones'), ('Earbuds', 'Earbuds')], default='Mens', max_length=20),
        ),
    ]
