# Generated by Django 5.2.4 on 2025-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('JAZZCASH', 'JazzCash / Easypaisa')], default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending Verification', 'Pending Verification'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mens_Unstitched', 'Mens_Unstititched'), ('Mens_stitched', 'Mens_stitched'), ('Womens_Unstitched', 'Womens_Unstitched'), ('Womens_stitched', 'Womens_stitched'), ('Watches', 'Watches'), ('Headphones', 'Headphones'), ('Earbuds', 'Earbuds')], default='Mens', max_length=20),
        ),
    ]
